### ISSUE TITLE
用嵌套 object 的 Schema 进行验证返回预期外的结果

### ISSUE THREAD

**Issue by Anillc** [Shigma/schemastery#1]
```javascript
a=Schema.object({a: Schema.object({b:Schema.number().default(1)})})
a({})
```

期待的结果:

```json
{
  "a": {
    "b": 1
  }
}
```

![image](https://user-images.githubusercontent.com/23411248/146876955-c62c8e53-5940-4554-a331-52c62bc52ef0.png)

**Comment by Shigma** [comment]
其实这个应该是预期结果，因为必须默认任何属性的值是 nullable，否则完全没有办法实现允许 nullable 类型的属性了。

你的问题应该改成：部分插件的 object schema 缺失 default 声明。

**Comment by Shigma** [comment]
然后对 intersection 内部的 object 会有另一个问题，即使设置了 default 也会失效，真正的 bug 其实是这里。

**Comment by Shigma** [comment]
Fixed
