### ISSUE TITLE
Schema.array() 渲染错误

### ISSUE THREAD

**Issue by arily** [shigma/schemastery#15]
增加新项后删除一条旧项，会渲染错误（第二项的内容被复制到第一项）
![58F37A06312C392DD8C788303FA65544](https://user-images.githubusercontent.com/10007589/183267182-c023ecaf-d55b-45f5-8294-da0add96dde6.jpg)
步骤：
- 按 1 增加项
- 按 2 删除
![AA6F0D5266C1761CBAFF54BECBE846B0](https://user-images.githubusercontent.com/10007589/183267185-fb7a778e-06df-43d0-a8e5-5569c5cd1d70.jpg)

**Comment by shigma** [comment]
这个已经好了是吗？

**Comment by arily** [comment]
对，具体不清楚什么时候好的。
