### ISSUE TITLE
feat request: `Schema.prototype.meta(key, value)`

### ISSUE THREAD

**Issue by undefined-moe** [shigma/schemastery#20]
```ts
const bar = Schema.dict(Schema.string().meta(key, value))
```

seems much better than

```ts
const foo = Schema.string();
foo.meta || = {};
foo.meta[key] = value
const bar = Schema.dict(foo)
```

**Comment by shigma** [comment]
`schema.meta` is not designed to be extensible, and the requested feature may lead to incompatible behavior. If you need more meta fields, please specify your needs directly.

**Comment by undefined-moe** [comment]
1. `Schema.string().pattern(regex)`
2. `Schema.string().examples(values)`
3. `Schema.string().deprecated()`
4. `Schema.array().minLength(min).maxLength(max)`

**Comment by shigma** [comment]
None of the ones you mentioned should be meta properties. You can request these features in separate issues.

**Comment by shigma** [comment]
Even if they are meta properties, I don't think this should be freely specified by the user. All constraints should be given by methods on the prototype chain.

**Comment by undefined-moe** [comment]
As meta field designed to be a dict with no type limitations, It should allow users store whatever they want, JSON-safe of course, and simply transmit the schema and what they need between backend and frontend. It provides a possibility. Otherwise, if an extra field is really needed in some special case, users might use something like `Schema.string().description('{"foo":1,"bar":true}')` and decode them in client-side, which I think would be much worse.

**Comment by shigma** [comment]
You have already given a workaround at the beginning of this issue, so the requested API is not necessary. Instead, the requested API increases vulnerability both in typings and runtime. If you just need `schema.example()` or other methods, PRs are always welcome.
