### ISSUE TITLE
bug: docs Union tagged 2 has unexpected behavior

### ISSUE THREAD

**Issue by Seidko** [shigma/schemastery#28]
### describe the bug

[Union tagged 2 docs](https://shigma.github.io/schemastery/composite/union-tagged-2.html) did't work as expected behavior.

### now behavior
When `enable` is true, the content in `Schema.object` is not being displayed.
<details> <summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/64234553/210517209-ec853500-572b-4441-b8d8-f5ae9323bc66.png)
</details>

### expected behavior

When `enable` is true, the content in `Schema.object` should be displayed.

**Comment by Seidko** [comment]
I have fixed this issue and will open a pull request tomorrow.

**Comment by shigma** [comment]
Despite this fix, I still consider it a bug.

**Comment by Seidko** [comment]
OK, I will keep this issue open. By the way, what is your expected code? Is it previous code?

**Comment by shigma** [comment]
> OK, I will keep this issue open. By the way, what is your expected code? Is it previous code?

Yes.
