### ISSUE TITLE
`Schema.array` 渲染错误

### ISSUE THREAD

**Issue by idanran** [shigma/schemastery#33]
当 `Schema.array(String).required()` 时，左侧没有出现红色标记。

版本：3.6.1

红色标记：
![image](https://user-images.githubusercontent.com/96647698/212945057-ebf51fd1-87a6-421f-aeae-b885bd74916c.png)

**Comment by shigma** [comment]
这是预期行为。array 有默认值，因此你什么都不写也相当于 `[]`，这样是没有红色标记的。

**Comment by idanran** [comment]
> 这是预期行为。array 有默认值，因此你什么都不写也相当于 `[]`，这样是没有红色标记的。

问题是浏览器控制台会报错。

**Comment by idanran** [comment]
嗯呐
