### ISSUE TITLE
feature requset: `Schema.union()` 支持使用其它参数的值

### ISSUE THREAD

**Issue by idanran** [shigma/schemastery#35]
Such as:
```
Schema.object({
 a: Schema.dict(Schema.number())
 b: Schema.union(Schema.dictKey('a'))
})

// 假设 Schema.dictKey('a') 可以获取到由 a 的 key 构成的数组
```
or
```
Schema.object({
 a: Schema.dict(Schema.number())
 b: Schema.union().bindDictKey('a')
})
```

**Comment by shigma** [comment]
这个暂时不会考虑。Schemastery 的定位是 Type Driven Database，我们目前只会考虑能对应 TypeScript 类型的表达。但你提出的使用场景是有效的，可以不用关闭。

**Comment by idanran** [comment]
> 这个暂时不会考虑。Schemastery 的定位是 Type Driven Schema Validator，我们目前只会考虑能对应 TypeScript 类型的表达。但你提出的使用场景是有效的，可以不用关闭。

好哒

**Comment by shigma** [comment]
现在完全可以这样写，并且更加清晰（而且还支持最新的 table 特性）：

```ts
Schema.object({
  a: Schema.dict(Schema.object({
    v: Schema.number(),
    e: Schema.boolean(),
  }),
})
```

**Comment by idanran** [comment]
> 现在完全可以这样写，并且更加清晰（而且还支持最新的 table 特性）：
> 
> ```ts
> Schema.object({
>   a: Schema.dict(Schema.object({
>     v: Schema.number(),
>     e: Schema.boolean(),
>   }),
> })
> ```

嗯呐
