### ISSUE TITLE
feature request: `Schema.dict` 支持对键名进行介绍

### ISSUE THREAD

**Issue by idanran** [shigma/schemastery#37]
Such as: `Schema.dict(Schema.string(), Schema.string().description('test'))`

![image](https://user-images.githubusercontent.com/96647698/215483850-5fda1f44-e1a1-4f4b-b34f-09eede1642c1.png)

**Comment by shigma** [comment]
Just try out

```ts
Schema.dict(Schema.string().description('test'), Schema.string())
```

**Comment by idanran** [comment]
> Just try out
> 
> ```ts
> Schema.dict(Schema.string().description('test'), Schema.string())
> ```

I want
```
Schema.dict(Schema.object({
        type: Schema.string().description('v')
}), Schema.string().description('test')),
```

**Comment by shigma** [comment]
Just try out

```ts
Schema.dict(Schema.object({
  type: Schema.string().description('v')
}).description('test'), Schema.string())
```

**Comment by idanran** [comment]
> Just try out
> 
> ```ts
> Schema.dict(Schema.object({
>   type: Schema.string().description('v')
> }).description('test'), Schema.string())
> ```

Solved, thanks.
