### ISSUE TITLE
Feature: 替换展示 label 文案

### ISSUE THREAD

**Issue by NWYLZW** [shigma/schemastery#39]
如果基于表单使用，存在一个问题
用户并不关心这个字段的英文名字，亦或是按照英文模式下 camelCase 实际上也不是正常的单词存在

建议增加一个描述语句专门去修改展示文案
```ts
{
  userName: schema.string()
    .label('用户名'),
  userName: schema.string()
    .label('User Name')
}
```

建议的待选：
label, displayText, plainText

如果可以我很乐意加上该功能

**Comment by shigma** [comment]
title？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by NWYLZW** [comment]
> title？
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

ok，晚点我发一个 pr

**Comment by NWYLZW** [comment]
等一下，这个可能和 html 语义中的默认的 tootip 字段产生冲突
浏览器的 hover 提示使用的字段是 title
我觉得换成 form 表单中的 label 比较合适

**Comment by shigma** [comment]
那就 label。

但其实需要指出不存在冲突，这里完全是显示在 h3 内部的，根本不是属性。如果考虑冲突的话我们不能提供任何使用了 title role style class 等字段的方法名了，这又不是关键字有什么不能用的？
