### ISSUE TITLE
Feature: 增加循环操作

### ISSUE THREAD

**Issue by NWYLZW** [shigma/schemastery#41]
# 原始场景

如果我需要一个重复类型的 `Tuple` 那么我只能如下去定义

```typescript
Schema.tuple([
  Schema.union([1, 2, 3]),
  Schema.union([1, 2, 3]),
  Schema.union([1, 2, 3])
])
```

# 建议

```typescript
// solution 0
Schema.tuple(Schema.union([1, 2, 3]).repeat(3))
Schema.tuple([
  ...Schema.union([1, 2, 3]).repeat(3)
])
// solution 1
Schema.tuple(Schema.union([1, 2, 3]), 3)
// solution 2
Schema.tuple(3).map(() => Schema.union([1, 2, 3]))
```

solution 0 的二状态的类型可能不好处理
solution 1 过于简单，场景复杂时基本不能用
solution 2 我认为是最灵活的！（ ~~我不是抄的 React~~ ）

# 别的想法

写着写着忘记了

**Comment by NWYLZW** [comment]
不过也可以全部都支持

**Comment by shigma** [comment]
😅😅😅 

```ts
Schema.tuple(Array(3).fill(0).map(_ => Schema.union([1, 2, 3])))
```

**Comment by NWYLZW** [comment]
> 😅😅😅
> 
> ```ts
> Schema.tuple(Array(3).fill(0).map(_ => Schema.union([1, 2, 3])))
> ```

我当然知道这么写，这样子类型会丢失

<img width="853" alt="image" src="https://user-images.githubusercontent.com/51358815/225548384-e651caa6-f8cf-4589-a997-88d2f1ba68eb.png">

**Comment by NWYLZW** [comment]
这样子只是处理了数据而已，但是 infer 类型的时候就会有问题了

**Comment by shigma** [comment]
我认为这个需求大概是今年看到的最没价值的了。

1. 能够被常数级代码替换的代码没有必要封装，fill 的核心是那个动态的 count，只要你数量确定，把内部 schema 拿出来做局部变量然后写三遍一定是可读性更好的。
2. 论类型的话，Schemastery 对照 TypeScript 类型系统，你这个已经远远 out of scope 了。
3. 这段代码本身的应用面可以说极窄，即便是在大规模使用的项目中我也几乎看不到具备实用价值的应用场景。
