### ISSUE TITLE
Feature: 获取 Dict 的 key

### ISSUE THREAD

**Issue by idanran** [shigma/schemastery#51]
```
export default Schema.object({
  dict: Schema.dict(Boolean),
  value2: Schema.union([])
})
```

我想让 dict 的所有 key，作为 value2 的选项。

**Comment by shigma** [comment]
姑且说一下我感觉不太好设计，因为 schemastery 需要对应于 TypeScript 的类型，而这个很难对应到具体的类型。

建议有两种改法：

1. dict 改成 object，一个 bool 表示你现在的 bool，另一个 bool 表示是否存在于 value2 里
2. 使用 dynamic schema，把上面的 dict 放到另一个插件中作为服务提供

**Comment by idanran** [comment]
> 姑且说一下我感觉不太好设计，因为 schemastery 需要对应于 TypeScript 的类型，而这个很难对应到具体的类型。
> 
> 建议有两种改法：
> 
> 1. dict 改成 object，一个 bool 表示你现在的 bool，另一个 bool 表示是否存在于 value2 里
> 2. 使用 dynamic schema，把上面的 dict 放到另一个插件中作为服务提供

或许可以做进 koishi 的 schema 服务

**Comment by shigma** [comment]
> 如果用第一种方法，可能没法让用户输入的内容成为union中的选择。也就是绑定一个 id，让所有含有这个 id 的输入框的值转化成一个数组，传递给 union。

但是用户**不需要**在 union 里选择，不需要这个 union 啊。你都做进 dict 了。

**Comment by idanran** [comment]
> 但是用户**不需要**在 union 里选择，不需要这个 union 啊。你都做进 dict 了。

业务需要…

**Comment by idanran** [comment]
> 那你写出来对应的 TypeScript 表达。

我好像还真写不出来，要不 T = any 吧（

**Comment by shigma** [comment]
> 我好像还真写不出来，要不 T = any 吧（

那就已经支持了：`Schema.any()`。

**Comment by shigma** [comment]
> 业务需要…

从表达能力的角度上面的方案是够的。你的业务与表达能力无关的话……你可以创建个页面来画。

**Comment by idanran** [comment]
…好吧
